### ISSUE TITLE
[TRACKING]  Complete support for CycloneDX v1.4

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python-lib#581]
see https://github.com/CycloneDX/specification/releases/tag/1.4

The following items are not currently supported for CycloneDX v1.4 (as of release 6.4.x):

- [ ] Missing `compositions` on `Bom`
    see via #607 
- [ ] Missing `properties` on `Bom`  
  - see #125
  - [ ] Support in v1.4
  - [x] Support in v1.5+ via #585
- [ ] JSF signatures
- to be continues

-----

this library is a community effort.
if you find a feature that you need is missing, feel free to donate/contribute the missing feature.
- see #633

**Comment by madpah** [comment]
Any reason you removed labels for 1.5 and 1.6 @jkowalleck - as these items are also missing from those versions?

**Comment by jkowalleck** [comment]
the issue is rooted on schema 1.4 - so this is the only label relevant for this.
of cause, all later schema versions are effected :-)

**Comment by jkowalleck** [comment]
@madpah, I opened this issue for public contribution
